### PR TITLE
Remove problematic dependency injection

### LINKED ISSUE #1: This module prevents being able to install `config_translation` module because of circular reference error
# Motivation
When attempting to enable the `config_translation` module, I received the following error:

```Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "entity_type.manager", path: "entity_type.manager -> string_translation -> string_translator.locale.lookup -> config.factory -> uiowa_auth.samlauth_override". in Drupal\Component\DependencyInjection\Container->get() (line 146 of core/lib/Drupal/Component/DependencyInjection/Container.php).```

I think this means that the following is an issue:
https://github.com/uiowa/uiowa_auth/blob/d93f30fe761874fe6f6890f89bbea4d06f9c6a15/src/ConfigOverride/SamlauthOverride.php#L24-L26

Here is an issue for the Domain module where they solved a similar issue: https://www.drupal.org/project/domain_site_settings/issues/2930391. It isn't immediately clear from the patch how it might apply to our situation, but maybe there is something in the discussion that might help.

# Proposed solution
It seems like we might not be able to use the `entity_type.manager` service to get the list of roles. Or mine the above link for ideas about what needs to be resolved.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #1

### CODE REVIEW

**Comment by pyrello** [comment]
I'm not sure why the build is erroring now. I'm trying to set `mglaman/drupal-check` to be less than `1.4`. This seems to not be working.

**Comment by joewhitsitt** [comment]
Sorry, I missed what you are trying to pin it at (besides less than 1.4). [1.3.2](https://github.com/mglaman/drupal-check/releases/tag/1.3.2)?

**Comment by pyrello** [comment]
I'm only trying to pin it at less than `1.4`

**Comment by joewhitsitt** [comment]
Locally, I got:
`  - Installing mglaman/drupal-check (1.3.2): Extracting archive`
Using: `"mglaman/drupal-check": "~1.3.1",`

**Comment by pyrello** [comment]
I got it to pass!

**Review by joewhitsitt — APPROVED** [review]
Reviewed, not tested. Wonder if once this is in uiowa, we can test in DEV?

**Comment by pyrello** [comment]
> Reviewed, not tested. Wonder if once this is in uiowa, we can test in DEV?

It will get tested in dev because I'm going to update it in the WhitmanWeb PR :)

**Pull request merged**
